### ISSUE TITLE
Your 'this' doesn't reference to window, causing errors in strict environment. 

### ISSUE THREAD

**Issue by indigo-sam** [constancecchen/object-fit-polyfill#10]
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD - registered as an anonymous module
    define(factory);
  } else if (typeof exports === "object") {
    // CommonJS
    module.exports = factory();
  } else {
    // Browser global
    root.objectFitPolyfill = factory();
  }
})(this, function () {...   //'this' in a strict environment would reference to 'undefined' thus creating an undefined error.

**Comment by cee-chen** [comment]
Could you please confirm (and preferably take screenshots) of any errors being thrown?

The above code is a very common [Universal Module Definition](https://github.com/umdjs/umd/) pattern for Javascript modules. I would strongly prefer not to change a pattern that isn't mine, since `this` changes depending on whether the environment is the browser, Node, etc (more info in [this Stackoverflow discussion](https://stackoverflow.com/questions/32659231/javascript-umd-where-how-are-root-factory-defined) and also [this article](https://toddmotto.com/what-function-window-document-undefined-iife-really-means/#non-browser-global-environments)).

**Comment by indigo-sam** [comment]
Oh that would make sense if they use the plugin in Node to reference different object. I was using babel and it automatically add a global 'use strict'. The 'this' would be forced to be an undefined instead of window object, but I see why it should be 'this' instead of window now. I guess I have to use different babel preset plugin to turn off global 'use strict'.

**Comment by cee-chen** [comment]
Thanks Sam! Looks like if you're using Babel 6, you can just not include the `strict-mode` plugin. This [Stackoverflow question](https://stackoverflow.com/questions/33821312/how-to-remove-global-use-strict-added-by-babel) might help? :)
