### ISSUE TITLE
Doesn't trigger on page change

### ISSUE THREAD

**Issue by Sawtaytoes** [constancecchen/object-fit-polyfill#13]
After reading through the code, this runs on page load and resize. If the URL changes through React, the script does not get reloaded and thus the `objectFitPolyfill` isn't called again. Is it possible to trigger the `objectFitPolyfill` function on URL change?

**Comment by cee-chen** [comment]
Yeah, totally! Just add your own hook for it. It's been a while since I've worked with React, but I believe React has some native behavior for this out of the box. I don't remember the exact hooks, but it would be better to watch for a page/state change rather than URL. Either way, here's a sample vanilla JS snippet which watches for a change in the browser's history:

```js
window.addEventListener("popstate", function () {
  objectFitPolyfill();
});
```

Depending on your routing you may want `hashchange` (watches the URL bar for # changes) instead of `popstate` :)
