### ISSUE TITLE
Lazy loading src 

### ISSUE THREAD

**Issue by tomgreenhill** [constancecchen/object-fit-polyfill#21]
First off, thank you! I have a potential feature request.

Is it possible to use or update this script with lazyloading images that have the image src on data-src?

**Comment by cee-chen** [comment]
Hey there!

Unfortunately there's a huge variety of lazyloading plugins - some which use data-src, and some which don't, some which use 1px sprites/placeholder images or inline 64 base encoded images, and some which use color gradients, etc, etc... it's quite difficult to guess at possible behaviors, and as such supporting lazyloading (a non-native behavior in the first place) would be outside the scope of this polyfill.

Your best bet would be to find a lazyloading plugin which has a trigger or hook event that you can use - and when an image or set of images is loaded in, simply re-run `objectFitPolyfill()` each time. If your plugin doesn't have a trigger event, you might have to manually create one based on the user's scroll position.

**Comment by tomgreenhill** [comment]
hey @constancecchen! Thanks a lot for replying. What you've said makes total sense and I completely understand! I guess I hadn't thought through the implications of the question fully! 

Would there be any scope for adding a hook or is that not something you require for this one?

Thanks again!

**Comment by cee-chen** [comment]
No worries at all! I hadn't thought through the interaction of lazyloading + object-fit previously myself, and it's a very interesting use-case. If I ever see a good solution for this problem in the future, I'll definitely let you know. (In a _perfect_ world, of course, IE Edge would start supporting `object-fit`, and evergreen sites wouldn't have to use this polyfill anymore 😄)

Regarding adding a hook: that would be within the scope of the lazyload plugin instead of this polyfill. Here's an excellent example of a lazyload plugin that offers an event callback:

### [Unveil.js](https://luis-almeida.github.io/unveil/)
```js
$("img").unveil(200, function() {
  objectFitPolyfill();
});
```

**Comment by tomgreenhill** [comment]
Nor I until now! Exactly, but sadly that utopia doesn't exist...yet! Awesome thank yoU!

Haha, yeah of course it would, sorry I was confusing myself as to what repo I was replying to! It's been an incredibly long few weeks! I had looked at Unveil, but I think there was a reason I couldn't roll with it, but will take a look! Thanks again.

**Comment by tomgreenhill** [comment]
Ha I really am being incredibly slow, I wanted to avoid jQuery! Thanks again though!

**Comment by hendrikeng** [comment]
@maketimetodesign I just use @constancecchen 's objectFitPloyfill for all the non-lazy loading images.
LazySizes itself comes with an own polyfill so i guess there isn't really a need to include it here.

Thanks for the great work @constancecchen
