### ISSUE TITLE
Possibility to give an element as parameter

### ISSUE THREAD

**Issue by cedeber** [constancecchen/object-fit-polyfill#27]
As `objectFitPolyfill` is already declared on `window`, I think that to add a parameter to it would be usefull so that we can use it with lazy loading images.

Something like this works well:
```javascript
var objectFitPolyfill = function(element) {
    var media = typeof element === "undefined" ? document.querySelectorAll("[data-object-fit]") : [element];
    [..]
}
```

What do you think about that?

**Comment by cee-chen** [comment]
Yes, this is definitely something I'd like to do! Apologies for dropping off the grid for a bit here, I've been incredibly swamped with side work. I promise I'll get around to this! :)

**Comment by cee-chen** [comment]
This is now possible as of v2.0.5! While I was at it I added support for multiple DOM elements (jQuery or querySelectorAll arrays) - figured I might as well not make people add another for loop, since I'm already doing it :)

You can check the added code [here](https://github.com/constancecchen/object-fit-polyfill/commit/e3b2ca89d23572ad3c5a75dd5fdfc75583d20008#diff-bbf4d48a48bce29e2ff6a6d16d614452) if you're curious.

**Comment by cedeber** [comment]
Hello. Now it's perfect! Thank you.
