### ISSUE TITLE
Not working in Edge 16

### ISSUE THREAD

**Issue by Roywcm** [constancecchen/object-fit-polyfill#33]
Hi,

Since Edge 16 is on the market, this polyfill is not working for video's anymore.
Edge 16 is now supporting object-fit only for images. I think the scripts is not working because it thinks objectfit is supported for the Edge 16?

**Comment by tuimz** [comment]
+1 here

**Comment by cee-chen** [comment]
<img src="http://a1.cdn.whatstrending.com/post_items/images/000/022/179/large_gif/summer-work-4.gif" alt="[screaming internally]">

**Comment by cee-chen** [comment]
OK... the latest update should've accounted for this. Let me know if it's working for you or not.

It's using browser sniffing which is horrible and sucky but I don't know a better way of ascertaining Edge 16. If someone knows or comes across a better way, feel free to leave a comment or ping me.

It's also not even remotely future proof since I have no god damn idea when Edge will get its shit together and implement object-fit correctly (17? 18? A minor semver of 16? Who knows!) so I'm gonna rely on you guys to open up more issues for me once anything changes :)
