### ISSUE TITLE
merge / collaborate with bfred-it/object-fit-images?

### ISSUE THREAD

**Issue by DanielRuf** [constancecchen/object-fit-polyfill#34]
It would be great to see some collaboration (isn't GitHub for this?) and see both solutions in one library to make it easier to decide which one to use.

**Comment by cee-chen** [comment]
[bfred-it/object-fit-images](https://github.com/bfred-it/object-fit-images#alternative-solutions) already has a super handy table comparison of features - is that sufficient for helping decide which to use?

Collaboration definitely sounds rad, and I think we actually recommend/link to one another! But they're just two different (and totally valid!) methods of approaching the problem, so it's not like we can share code or anything really :)

Closing this for now due to inactivity/since it's been open so long without anyone stepping up to volunteer, but feel free to re-open if you have any action items/suggestions in the future!
