### ISSUE TITLE
is not a function

### ISSUE THREAD

**Issue by ease-space** [constancecchen/object-fit-polyfill#54]
TypeError: objectFitPolyfill__WEBPACK_IMPORTED_MODULE_6___default(...) is not a function
![Снимок](https://user-images.githubusercontent.com/23016311/60757101-0035f300-a00f-11e9-9a6e-5a28934a1bdd.PNG)
![Снимок1](https://user-images.githubusercontent.com/23016311/60757102-0035f300-a00f-11e9-89ce-ea81a2893204.PNG)

**Comment by golubvladimir** [comment]
`import 'objectFitPolyfill';`

**Comment by brycebenson** [comment]
You can use it like it this in React (with `react-video`):

`helpers.js`
```
import 'objectFitPolyfill';

export const vidHelper = () => {
	const vids = Array.from(document.querySelectorAll('.video-react-video'));
	vids.forEach(vid => {
		vid.setAttribute('data-object-fit', 'cover');
		vid.setAttribute('data-object-position', 'center center');
	})
	window.objectFitPolyfill();
};
```

Import that into your component/root component, and add :
`myComp.js` 
```
import { vidHelper } from '../../helpers'
...

componentDidMount() {
    vidHelper();
  }
```

You''ll need `babel-polyfill` also in your app to get it all working in IE11.

**Comment by roydukkey** [comment]
We probably should be creating a `@types/objectFitPolyfill` package. http://blog.wolksoftware.com/contributing-to-definitelytyped

**Comment by cee-chen** [comment]
Closing this issue as I've added @brycebenson's super helpful instructions + a link to his comment in the README (so this will hopefully trip up less folks going forward, apologies this took so long).

@roydukkey, I'd definitely be happy to take a PR for types, but not sure I have the bandwidth to do so myself - feel free to open a separate issue for that!

EDIT: I had a little bit of time today and turns out the typescript defs are much easier than I thought (no `@types` package needed either), since the polyfill is a [super small global library](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-d-ts.html). I've added a `global.d.ts` file as of version 2.3.4 that should quiet any Typescript complaints when using `window.objectFitPolyfill()`.
